/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.vehicle_journey.tables.records


import fi.hsl.jore.jore4.jooq.vehicle_journey.tables.JourneyType

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * Enum table for defining allowed journey types.
 */
@Suppress("UNCHECKED_CAST")
open class JourneyTypeRecord private constructor() : UpdatableRecordImpl<JourneyTypeRecord>(JourneyType.JOURNEY_TYPE) {

    open var type: String
        set(value): Unit = set(0, value)
        get(): String = get(0) as String

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised JourneyTypeRecord
     */
    constructor(type: String): this() {
        this.type = type
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised JourneyTypeRecord
     */
    constructor(value: fi.hsl.jore.jore4.jooq.vehicle_journey.tables.pojos.JourneyType?): this() {
        if (value != null) {
            this.type = value.type
            resetChangedOnNotNull()
        }
    }
}
