/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.vehicle_journey.tables.records


import fi.hsl.jore.jore4.jooq.vehicle_journey.tables.VehicleJourney

import java.util.UUID

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.jooq.types.YearToSecond


/**
 * The planned movement of a public transport vehicle on a DAY TYPE from the
 * start point to the end point of a JOURNEY PATTERN on a specified ROUTE.
 * Transmodel: https://www.transmodel-cen.eu/model/index.htm?goto=3:1:1:831 
 */
@Suppress("UNCHECKED_CAST")
open class VehicleJourneyRecord private constructor() : UpdatableRecordImpl<VehicleJourneyRecord>(VehicleJourney.VEHICLE_JOURNEY_) {

    open var vehicleJourneyId: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var journeyPatternRefId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var blockId: UUID
        set(value): Unit = set(2, value)
        get(): UUID = get(2) as UUID

    open var journeyNameI18n: JSONB?
        set(value): Unit = set(3, value)
        get(): JSONB? = get(3) as JSONB?

    open var turnaroundTime: YearToSecond?
        set(value): Unit = set(4, value)
        get(): YearToSecond? = get(4) as YearToSecond?

    open var layoverTime: YearToSecond?
        set(value): Unit = set(5, value)
        get(): YearToSecond? = get(5) as YearToSecond?

    open var journeyType: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var displayedName: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsVehicleTypeMandatory")
    open var isVehicleTypeMandatory: Boolean?
        set(value): Unit = set(8, value)
        get(): Boolean? = get(8) as Boolean?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsBackupJourney")
    open var isBackupJourney: Boolean?
        set(value): Unit = set(9, value)
        get(): Boolean? = get(9) as Boolean?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsExtraJourney")
    open var isExtraJourney: Boolean?
        set(value): Unit = set(10, value)
        get(): Boolean? = get(10) as Boolean?

    open var contractNumber: String
        set(value): Unit = set(11, value)
        get(): String = get(11) as String

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised VehicleJourneyRecord
     */
    constructor(vehicleJourneyId: UUID? = null, journeyPatternRefId: UUID, blockId: UUID, journeyNameI18n: JSONB? = null, turnaroundTime: YearToSecond? = null, layoverTime: YearToSecond? = null, journeyType: String? = null, displayedName: String? = null, isVehicleTypeMandatory: Boolean? = null, isBackupJourney: Boolean? = null, isExtraJourney: Boolean? = null, contractNumber: String): this() {
        this.vehicleJourneyId = vehicleJourneyId
        this.journeyPatternRefId = journeyPatternRefId
        this.blockId = blockId
        this.journeyNameI18n = journeyNameI18n
        this.turnaroundTime = turnaroundTime
        this.layoverTime = layoverTime
        this.journeyType = journeyType
        this.displayedName = displayedName
        this.isVehicleTypeMandatory = isVehicleTypeMandatory
        this.isBackupJourney = isBackupJourney
        this.isExtraJourney = isExtraJourney
        this.contractNumber = contractNumber
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised VehicleJourneyRecord
     */
    constructor(value: fi.hsl.jore.jore4.jooq.vehicle_journey.tables.pojos.VehicleJourney?): this() {
        if (value != null) {
            this.vehicleJourneyId = value.vehicleJourneyId
            this.journeyPatternRefId = value.journeyPatternRefId
            this.blockId = value.blockId
            this.journeyNameI18n = value.journeyNameI18n
            this.turnaroundTime = value.turnaroundTime
            this.layoverTime = value.layoverTime
            this.journeyType = value.journeyType
            this.displayedName = value.displayedName
            this.isVehicleTypeMandatory = value.isVehicleTypeMandatory
            this.isBackupJourney = value.isBackupJourney
            this.isExtraJourney = value.isExtraJourney
            this.contractNumber = value.contractNumber
            resetChangedOnNotNull()
        }
    }
}
