/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.vehicle_journey.tables.records


import fi.hsl.jore.jore4.jooq.vehicle_journey.tables.VehicleJourney

import java.util.UUID

import org.jooq.Field
import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.Record11
import org.jooq.Row11
import org.jooq.impl.UpdatableRecordImpl
import org.jooq.types.YearToSecond


/**
 * The planned movement of a public transport vehicle on a DAY TYPE from the
 * start point to the end point of a JOURNEY PATTERN on a specified ROUTE.
 * Transmodel: https://www.transmodel-cen.eu/model/index.htm?goto=3:1:1:831 
 */
@Suppress("UNCHECKED_CAST")
open class VehicleJourneyRecord() : UpdatableRecordImpl<VehicleJourneyRecord>(VehicleJourney.VEHICLE_JOURNEY_), Record11<UUID?, UUID?, UUID?, JSONB?, YearToSecond?, YearToSecond?, String?, String?, Boolean?, Boolean?, Boolean?> {

    open var vehicleJourneyId: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var journeyPatternRefId: UUID?
        set(value): Unit = set(1, value)
        get(): UUID? = get(1) as UUID?

    open var blockId: UUID?
        set(value): Unit = set(2, value)
        get(): UUID? = get(2) as UUID?

    open var journeyNameI18n: JSONB?
        set(value): Unit = set(3, value)
        get(): JSONB? = get(3) as JSONB?

    open var turnaroundTime: YearToSecond?
        set(value): Unit = set(4, value)
        get(): YearToSecond? = get(4) as YearToSecond?

    open var layoverTime: YearToSecond?
        set(value): Unit = set(5, value)
        get(): YearToSecond? = get(5) as YearToSecond?

    open var journeyType: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var displayedName: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsVehicleTypeMandatory")
    open var isVehicleTypeMandatory: Boolean?
        set(value): Unit = set(8, value)
        get(): Boolean? = get(8) as Boolean?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsBackupJourney")
    open var isBackupJourney: Boolean?
        set(value): Unit = set(9, value)
        get(): Boolean? = get(9) as Boolean?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsExtraJourney")
    open var isExtraJourney: Boolean?
        set(value): Unit = set(10, value)
        get(): Boolean? = get(10) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row11<UUID?, UUID?, UUID?, JSONB?, YearToSecond?, YearToSecond?, String?, String?, Boolean?, Boolean?, Boolean?> = super.fieldsRow() as Row11<UUID?, UUID?, UUID?, JSONB?, YearToSecond?, YearToSecond?, String?, String?, Boolean?, Boolean?, Boolean?>
    override fun valuesRow(): Row11<UUID?, UUID?, UUID?, JSONB?, YearToSecond?, YearToSecond?, String?, String?, Boolean?, Boolean?, Boolean?> = super.valuesRow() as Row11<UUID?, UUID?, UUID?, JSONB?, YearToSecond?, YearToSecond?, String?, String?, Boolean?, Boolean?, Boolean?>
    override fun field1(): Field<UUID?> = VehicleJourney.VEHICLE_JOURNEY_.VEHICLE_JOURNEY_ID
    override fun field2(): Field<UUID?> = VehicleJourney.VEHICLE_JOURNEY_.JOURNEY_PATTERN_REF_ID
    override fun field3(): Field<UUID?> = VehicleJourney.VEHICLE_JOURNEY_.BLOCK_ID
    override fun field4(): Field<JSONB?> = VehicleJourney.VEHICLE_JOURNEY_.JOURNEY_NAME_I18N
    override fun field5(): Field<YearToSecond?> = VehicleJourney.VEHICLE_JOURNEY_.TURNAROUND_TIME
    override fun field6(): Field<YearToSecond?> = VehicleJourney.VEHICLE_JOURNEY_.LAYOVER_TIME
    override fun field7(): Field<String?> = VehicleJourney.VEHICLE_JOURNEY_.JOURNEY_TYPE
    override fun field8(): Field<String?> = VehicleJourney.VEHICLE_JOURNEY_.DISPLAYED_NAME
    override fun field9(): Field<Boolean?> = VehicleJourney.VEHICLE_JOURNEY_.IS_VEHICLE_TYPE_MANDATORY
    override fun field10(): Field<Boolean?> = VehicleJourney.VEHICLE_JOURNEY_.IS_BACKUP_JOURNEY
    override fun field11(): Field<Boolean?> = VehicleJourney.VEHICLE_JOURNEY_.IS_EXTRA_JOURNEY
    override fun component1(): UUID? = vehicleJourneyId
    override fun component2(): UUID? = journeyPatternRefId
    override fun component3(): UUID? = blockId
    override fun component4(): JSONB? = journeyNameI18n
    override fun component5(): YearToSecond? = turnaroundTime
    override fun component6(): YearToSecond? = layoverTime
    override fun component7(): String? = journeyType
    override fun component8(): String? = displayedName
    override fun component9(): Boolean? = isVehicleTypeMandatory
    override fun component10(): Boolean? = isBackupJourney
    override fun component11(): Boolean? = isExtraJourney
    override fun value1(): UUID? = vehicleJourneyId
    override fun value2(): UUID? = journeyPatternRefId
    override fun value3(): UUID? = blockId
    override fun value4(): JSONB? = journeyNameI18n
    override fun value5(): YearToSecond? = turnaroundTime
    override fun value6(): YearToSecond? = layoverTime
    override fun value7(): String? = journeyType
    override fun value8(): String? = displayedName
    override fun value9(): Boolean? = isVehicleTypeMandatory
    override fun value10(): Boolean? = isBackupJourney
    override fun value11(): Boolean? = isExtraJourney

    override fun value1(value: UUID?): VehicleJourneyRecord {
        set(0, value)
        return this
    }

    override fun value2(value: UUID?): VehicleJourneyRecord {
        set(1, value)
        return this
    }

    override fun value3(value: UUID?): VehicleJourneyRecord {
        set(2, value)
        return this
    }

    override fun value4(value: JSONB?): VehicleJourneyRecord {
        set(3, value)
        return this
    }

    override fun value5(value: YearToSecond?): VehicleJourneyRecord {
        set(4, value)
        return this
    }

    override fun value6(value: YearToSecond?): VehicleJourneyRecord {
        set(5, value)
        return this
    }

    override fun value7(value: String?): VehicleJourneyRecord {
        set(6, value)
        return this
    }

    override fun value8(value: String?): VehicleJourneyRecord {
        set(7, value)
        return this
    }

    override fun value9(value: Boolean?): VehicleJourneyRecord {
        set(8, value)
        return this
    }

    override fun value10(value: Boolean?): VehicleJourneyRecord {
        set(9, value)
        return this
    }

    override fun value11(value: Boolean?): VehicleJourneyRecord {
        set(10, value)
        return this
    }

    override fun values(value1: UUID?, value2: UUID?, value3: UUID?, value4: JSONB?, value5: YearToSecond?, value6: YearToSecond?, value7: String?, value8: String?, value9: Boolean?, value10: Boolean?, value11: Boolean?): VehicleJourneyRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        return this
    }

    /**
     * Create a detached, initialised VehicleJourneyRecord
     */
    constructor(vehicleJourneyId: UUID? = null, journeyPatternRefId: UUID? = null, blockId: UUID? = null, journeyNameI18n: JSONB? = null, turnaroundTime: YearToSecond? = null, layoverTime: YearToSecond? = null, journeyType: String? = null, displayedName: String? = null, isVehicleTypeMandatory: Boolean? = null, isBackupJourney: Boolean? = null, isExtraJourney: Boolean? = null): this() {
        this.vehicleJourneyId = vehicleJourneyId
        this.journeyPatternRefId = journeyPatternRefId
        this.blockId = blockId
        this.journeyNameI18n = journeyNameI18n
        this.turnaroundTime = turnaroundTime
        this.layoverTime = layoverTime
        this.journeyType = journeyType
        this.displayedName = displayedName
        this.isVehicleTypeMandatory = isVehicleTypeMandatory
        this.isBackupJourney = isBackupJourney
        this.isExtraJourney = isExtraJourney
        resetChangedOnNotNull()
    }
}
