/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.pg_catalog.routines


import fi.hsl.jore.jore4.jooq.pg_catalog.PgCatalog

import org.jooq.impl.AbstractRoutine


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PgStatClearSnapshot : AbstractRoutine<java.lang.Void>("pg_stat_clear_snapshot", PgCatalog.PG_CATALOG) {
    companion object {
    }

    init {
    }
}
