/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.internal_utils.routines


import fi.hsl.jore.jore4.jooq.internal_utils.InternalUtils

import org.jooq.impl.AbstractRoutine


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CreateValidationQueueTempTables : AbstractRoutine<java.lang.Void>("create_validation_queue_temp_tables", InternalUtils.INTERNAL_UTILS) {
    companion object {
    }

    init {
    }
}
