/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.service_calendar.routines.references


import fi.hsl.jore.jore4.jooq.service_calendar.routines.ConstOperatingDayEndTime
import fi.hsl.jore.jore4.jooq.service_calendar.routines.ConstOperatingDayStartTime
import fi.hsl.jore.jore4.jooq.service_calendar.tables.GetActiveDayTypesForDate
import fi.hsl.jore.jore4.jooq.service_calendar.tables.records.DayTypeRecord

import java.time.LocalDate

import org.jooq.Configuration
import org.jooq.Field
import org.jooq.Result
import org.jooq.types.YearToSecond



/**
 * Call <code>service_calendar.const_operating_day_end_time</code>
 */
fun constOperatingDayEndTime(
      configuration: Configuration
): YearToSecond? {
    val f = ConstOperatingDayEndTime()

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>service_calendar.const_operating_day_end_time</code> as a field.
 */
fun constOperatingDayEndTime(): Field<YearToSecond?> {
    val f = ConstOperatingDayEndTime()

    return f.asField()
}

/**
 * Call <code>service_calendar.const_operating_day_start_time</code>
 */
fun constOperatingDayStartTime(
      configuration: Configuration
): YearToSecond? {
    val f = ConstOperatingDayStartTime()

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>service_calendar.const_operating_day_start_time</code> as a field.
 */
fun constOperatingDayStartTime(): Field<YearToSecond?> {
    val f = ConstOperatingDayStartTime()

    return f.asField()
}

/**
 * Call <code>service_calendar.get_active_day_types_for_date</code>.
 */
fun getActiveDayTypesForDate(
      configuration: Configuration
    , observationDate: LocalDate?
): Result<DayTypeRecord> = configuration.dsl().selectFrom(fi.hsl.jore.jore4.jooq.service_calendar.tables.GetActiveDayTypesForDate.GET_ACTIVE_DAY_TYPES_FOR_DATE.call(
      observationDate
)).fetch()

/**
 * Get <code>service_calendar.get_active_day_types_for_date</code> as a table.
 */
fun getActiveDayTypesForDate(
      observationDate: LocalDate?
): GetActiveDayTypesForDate = fi.hsl.jore.jore4.jooq.service_calendar.tables.GetActiveDayTypesForDate.GET_ACTIVE_DAY_TYPES_FOR_DATE.call(
    observationDate
)

/**
 * Get <code>service_calendar.get_active_day_types_for_date</code> as a table.
 */
fun getActiveDayTypesForDate(
      observationDate: Field<LocalDate?>
): GetActiveDayTypesForDate = fi.hsl.jore.jore4.jooq.service_calendar.tables.GetActiveDayTypesForDate.GET_ACTIVE_DAY_TYPES_FOR_DATE.call(
    observationDate
)
