/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.pg_catalog.tables


import fi.hsl.jore.jore4.jooq.pg_catalog.PgCatalog

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PgAvailableExtensions(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?
): TableImpl<Record>(
    alias,
    PgCatalog.PG_CATALOG,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.function()
) {
    companion object {

        /**
         * The reference instance of
         * <code>pg_catalog.pg_available_extensions</code>
         */
        val PG_AVAILABLE_EXTENSIONS: PgAvailableExtensions = PgAvailableExtensions()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>pg_catalog.pg_available_extensions.name</code>.
     */
    val NAME: TableField<Record, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>pg_catalog.pg_available_extensions.default_version</code>.
     */
    val DEFAULT_VERSION: TableField<Record, String?> = createField(DSL.name("default_version"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>pg_catalog.pg_available_extensions.comment</code>.
     */
    val COMMENT: TableField<Record, String?> = createField(DSL.name("comment"), SQLDataType.CLOB, this, "")

    private constructor(alias: Name, aliased: Table<Record>?): this(alias, null, null, aliased, arrayOf(
    ))
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>pg_catalog.pg_available_extensions</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>pg_catalog.pg_available_extensions</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>pg_catalog.pg_available_extensions</code> table reference
     */
    constructor(): this(DSL.name("pg_available_extensions"), null)
    override fun getSchema(): Schema? = if (aliased()) null else PgCatalog.PG_CATALOG
    override fun `as`(alias: String): PgAvailableExtensions = PgAvailableExtensions(DSL.name(alias), this, parameters)
    override fun `as`(alias: Name): PgAvailableExtensions = PgAvailableExtensions(alias, this, parameters)

    /**
     * Rename this table
     */
    override fun rename(name: String): PgAvailableExtensions = PgAvailableExtensions(DSL.name(name), null, parameters)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PgAvailableExtensions = PgAvailableExtensions(name, null, parameters)

    /**
     * Call this table-valued function
     */
    fun call(): PgAvailableExtensions = PgAvailableExtensions(DSL.name("pg_available_extensions"), null, arrayOf()).let { if (aliased()) it.`as`(unqualifiedName) else it }
}
