/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.pg_catalog.tables


import fi.hsl.jore.jore4.jooq.pg_catalog.PgCatalog

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PgUserMappings(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?
): TableImpl<Record>(
    alias,
    PgCatalog.PG_CATALOG,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.view()
) {
    companion object {

        /**
         * The reference instance of <code>pg_catalog.pg_user_mappings</code>
         */
        val PG_USER_MAPPINGS: PgUserMappings = PgUserMappings()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>pg_catalog.pg_user_mappings.umid</code>.
     */
    val UMID: TableField<Record, Long?> = createField(DSL.name("umid"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>pg_catalog.pg_user_mappings.srvid</code>.
     */
    val SRVID: TableField<Record, Long?> = createField(DSL.name("srvid"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>pg_catalog.pg_user_mappings.srvname</code>.
     */
    val SRVNAME: TableField<Record, String?> = createField(DSL.name("srvname"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>pg_catalog.pg_user_mappings.umuser</code>.
     */
    val UMUSER: TableField<Record, Long?> = createField(DSL.name("umuser"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>pg_catalog.pg_user_mappings.usename</code>.
     */
    val USENAME: TableField<Record, String?> = createField(DSL.name("usename"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>pg_catalog.pg_user_mappings.umoptions</code>.
     */
    val UMOPTIONS: TableField<Record, Array<String?>?> = createField(DSL.name("umoptions"), SQLDataType.CLOB.getArrayDataType(), this, "")

    private constructor(alias: Name, aliased: Table<Record>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>pg_catalog.pg_user_mappings</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>pg_catalog.pg_user_mappings</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>pg_catalog.pg_user_mappings</code> table reference
     */
    constructor(): this(DSL.name("pg_user_mappings"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, Record>): this(Internal.createPathAlias(child, key), child, key, PG_USER_MAPPINGS, null)
    override fun getSchema(): Schema? = if (aliased()) null else PgCatalog.PG_CATALOG
    override fun `as`(alias: String): PgUserMappings = PgUserMappings(DSL.name(alias), this)
    override fun `as`(alias: Name): PgUserMappings = PgUserMappings(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PgUserMappings = PgUserMappings(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PgUserMappings = PgUserMappings(name, null)
}
