/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.pg_catalog.tables


import fi.hsl.jore.jore4.jooq.pg_catalog.PgCatalog

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Unnest(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?
): TableImpl<Record>(
    alias,
    PgCatalog.PG_CATALOG,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.function()
) {
    companion object {

        /**
         * The reference instance of <code>pg_catalog.unnest</code>
         */
        val UNNEST: Unnest = Unnest()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>pg_catalog.unnest.lexeme</code>.
     */
    val LEXEME: TableField<Record, String?> = createField(DSL.name("lexeme"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>pg_catalog.unnest.positions</code>.
     */
    val POSITIONS: TableField<Record, Array<Short?>?> = createField(DSL.name("positions"), SQLDataType.SMALLINT.getArrayDataType(), this, "")

    /**
     * The column <code>pg_catalog.unnest.weights</code>.
     */
    val WEIGHTS: TableField<Record, Array<String?>?> = createField(DSL.name("weights"), SQLDataType.CLOB.getArrayDataType(), this, "")

    private constructor(alias: Name, aliased: Table<Record>?): this(alias, null, null, aliased, arrayOf(
        DSL.value(null, org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"tsvector\""))
    ))
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>pg_catalog.unnest</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>pg_catalog.unnest</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>pg_catalog.unnest</code> table reference
     */
    constructor(): this(DSL.name("unnest"), null)
    override fun getSchema(): Schema? = if (aliased()) null else PgCatalog.PG_CATALOG
    override fun `as`(alias: String): Unnest = Unnest(DSL.name(alias), this, parameters)
    override fun `as`(alias: Name): Unnest = Unnest(alias, this, parameters)

    /**
     * Rename this table
     */
    override fun rename(name: String): Unnest = Unnest(DSL.name(name), null, parameters)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Unnest = Unnest(name, null, parameters)

    /**
     * Call this table-valued function
     */
    fun call(
          tsvector: Any?
    ): Unnest = Unnest(DSL.name("unnest"), null, arrayOf(
        DSL.value(tsvector, org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"tsvector\""))
    )).let { if (aliased()) it.`as`(unqualifiedName) else it }

    /**
     * Call this table-valued function
     */
    fun call(
          tsvector: Field<Any?>
    ): Unnest = Unnest(DSL.name("unnest"), null, arrayOf(
        tsvector
    )).let { if (aliased()) it.`as`(unqualifiedName) else it }
}
