---
version: "3.8"
services:
  # build and run the local image instead
  # note: it's currently expose on port 3009
  jore4-timetables-api:
    build:
      context: ".."
      network: host
    ports:
      - "127.0.0.1:3009:8080"
    networks:
      - jore4
    extra_hosts:
      - "host.docker.internal:host-gateway"

  jore4-hasura:
    # locking hasura image so that we can develop against a static graphql API
    # Link to available jore4-hasura images in Docker Hub:
    # https://hub.docker.com/r/hsldevcom/jore4-hasura/tags?page=1&ordering=last_updated
    image: "hsldevcom/jore4-hasura:hsl-main--20231011-bbd4c8750a5e09e115a8a1350ec9f6f10e43eb65"
    # Waiting for database to be ready to avoid startup delay due to hasura crashing at startup if db is offline
    # Note: this should only be done in development setups as Kubernetes does not allow waiting for services to be ready
    depends_on:
      jore4-testdb:
        condition: service_healthy
