---
services:
  # build and run the local image instead
  # note: it's currently expose on port 3009
  jore4-timetables-api:
    build:
      context: ".."
      network: host
    ports:
      - "127.0.0.1:3009:8080"
    networks:
      - jore4
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SECRET_STORE_BASE_PATH: "/mnt/secrets-store"
    secrets:
      - source: timetablesapi-jore4-db-database
        target: /mnt/secrets-store/jore4-db-database
      - source: timetablesapi-jore4-db-hostname
        target: /mnt/secrets-store/jore4-db-hostname
      - source: timetablesapi-jore4-db-password
        target: /mnt/secrets-store/jore4-db-password
      - source: timetablesapi-jore4-db-username
        target: /mnt/secrets-store/jore4-db-username

  jore4-hasura:
    # Waiting for database to be ready to avoid startup delay due to hasura crashing at startup if db is offline
    # Note: this should only be done in development setups as Kubernetes does not allow waiting for services to be ready
    depends_on:
      jore4-testdb:
        condition: service_healthy
