/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.service_calendar.tables.pojos


import java.io.Serializable
import java.util.UUID

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class GetActiveDayTypesForDate(
    var dayTypeId: UUID? = null,
    var label: String,
    var nameI18n: JSONB
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: GetActiveDayTypesForDate = other as GetActiveDayTypesForDate
        if (this.dayTypeId == null) {
            if (o.dayTypeId != null)
                return false
        }
        else if (this.dayTypeId != o.dayTypeId)
            return false
        if (this.label != o.label)
            return false
        if (this.nameI18n != o.nameI18n)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.dayTypeId == null) 0 else this.dayTypeId.hashCode())
        result = prime * result + this.label.hashCode()
        result = prime * result + this.nameI18n.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("GetActiveDayTypesForDate (")

        sb.append(dayTypeId)
        sb.append(", ").append(label)
        sb.append(", ").append(nameI18n)

        sb.append(")")
        return sb.toString()
    }
}
