/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.route.tables.references


import fi.hsl.jore.jore4.jooq.route.tables.TypeOfLine



/**
 * Type of line. https://www.transmodel-cen.eu/model/index.htm?goto=2:1:3:424
 */
val TYPE_OF_LINE: TypeOfLine = TypeOfLine.TYPE_OF_LINE
