/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.information_schema.tables


import fi.hsl.jore.jore4.jooq.information_schema.InformationSchema

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SqlPackages(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?
): TableImpl<Record>(
    alias,
    InformationSchema.INFORMATION_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>information_schema.sql_packages</code>
         */
        val SQL_PACKAGES = SqlPackages()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>information_schema.sql_packages.feature_id</code>.
     */
    val FEATURE_ID: TableField<Record, String?> = createField(DSL.name("feature_id"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>information_schema.sql_packages.feature_name</code>.
     */
    val FEATURE_NAME: TableField<Record, String?> = createField(DSL.name("feature_name"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>information_schema.sql_packages.is_supported</code>.
     */
    val IS_SUPPORTED: TableField<Record, String?> = createField(DSL.name("is_supported"), SQLDataType.VARCHAR(3), this, "")

    /**
     * The column <code>information_schema.sql_packages.is_verified_by</code>.
     */
    val IS_VERIFIED_BY: TableField<Record, String?> = createField(DSL.name("is_verified_by"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>information_schema.sql_packages.comments</code>.
     */
    val COMMENTS: TableField<Record, String?> = createField(DSL.name("comments"), SQLDataType.VARCHAR, this, "")

    private constructor(alias: Name, aliased: Table<Record>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>information_schema.sql_packages</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>information_schema.sql_packages</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>information_schema.sql_packages</code> table reference
     */
    constructor(): this(DSL.name("sql_packages"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, Record>): this(Internal.createPathAlias(child, key), child, key, SQL_PACKAGES, null)
    override fun getSchema(): Schema = InformationSchema.INFORMATION_SCHEMA
    override fun `as`(alias: String): SqlPackages = SqlPackages(DSL.name(alias), this)
    override fun `as`(alias: Name): SqlPackages = SqlPackages(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SqlPackages = SqlPackages(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SqlPackages = SqlPackages(name, null)
}
