/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.information_schema.tables


import fi.hsl.jore.jore4.jooq.information_schema.InformationSchema

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SqlSizingProfiles(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?
): TableImpl<Record>(
    alias,
    InformationSchema.INFORMATION_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>information_schema.sql_sizing_profiles</code>
         */
        val SQL_SIZING_PROFILES: SqlSizingProfiles = SqlSizingProfiles()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>information_schema.sql_sizing_profiles.sizing_id</code>.
     */
    val SIZING_ID: TableField<Record, Int?> = createField(DSL.name("sizing_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>information_schema.sql_sizing_profiles.sizing_name</code>.
     */
    val SIZING_NAME: TableField<Record, String?> = createField(DSL.name("sizing_name"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.sql_sizing_profiles.profile_id</code>.
     */
    val PROFILE_ID: TableField<Record, String?> = createField(DSL.name("profile_id"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.sql_sizing_profiles.required_value</code>.
     */
    val REQUIRED_VALUE: TableField<Record, Int?> = createField(DSL.name("required_value"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>information_schema.sql_sizing_profiles.comments</code>.
     */
    val COMMENTS: TableField<Record, String?> = createField(DSL.name("comments"), SQLDataType.VARCHAR, this, "")

    private constructor(alias: Name, aliased: Table<Record>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>information_schema.sql_sizing_profiles</code>
     * table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>information_schema.sql_sizing_profiles</code>
     * table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>information_schema.sql_sizing_profiles</code> table
     * reference
     */
    constructor(): this(DSL.name("sql_sizing_profiles"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, Record>): this(Internal.createPathAlias(child, key), child, key, SQL_SIZING_PROFILES, null)
    override fun getSchema(): Schema? = if (aliased()) null else InformationSchema.INFORMATION_SCHEMA
    override fun `as`(alias: String): SqlSizingProfiles = SqlSizingProfiles(DSL.name(alias), this)
    override fun `as`(alias: Name): SqlSizingProfiles = SqlSizingProfiles(alias, this)
    override fun `as`(alias: Table<*>): SqlSizingProfiles = SqlSizingProfiles(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SqlSizingProfiles = SqlSizingProfiles(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SqlSizingProfiles = SqlSizingProfiles(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): SqlSizingProfiles = SqlSizingProfiles(name.getQualifiedName(), null)
}
