/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.information_schema.tables


import fi.hsl.jore.jore4.jooq.information_schema.InformationSchema

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserDefinedTypes(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?
): TableImpl<Record>(
    alias,
    InformationSchema.INFORMATION_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.view()
) {
    companion object {

        /**
         * The reference instance of
         * <code>information_schema.user_defined_types</code>
         */
        val USER_DEFINED_TYPES: UserDefinedTypes = UserDefinedTypes()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column
     * <code>information_schema.user_defined_types.user_defined_type_catalog</code>.
     */
    val USER_DEFINED_TYPE_CATALOG: TableField<Record, String?> = createField(DSL.name("user_defined_type_catalog"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.user_defined_type_schema</code>.
     */
    val USER_DEFINED_TYPE_SCHEMA: TableField<Record, String?> = createField(DSL.name("user_defined_type_schema"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.user_defined_type_name</code>.
     */
    val USER_DEFINED_TYPE_NAME: TableField<Record, String?> = createField(DSL.name("user_defined_type_name"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.user_defined_type_category</code>.
     */
    val USER_DEFINED_TYPE_CATEGORY: TableField<Record, String?> = createField(DSL.name("user_defined_type_category"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.is_instantiable</code>.
     */
    val IS_INSTANTIABLE: TableField<Record, String?> = createField(DSL.name("is_instantiable"), SQLDataType.VARCHAR(3), this, "")

    /**
     * The column <code>information_schema.user_defined_types.is_final</code>.
     */
    val IS_FINAL: TableField<Record, String?> = createField(DSL.name("is_final"), SQLDataType.VARCHAR(3), this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.ordering_form</code>.
     */
    val ORDERING_FORM: TableField<Record, String?> = createField(DSL.name("ordering_form"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.ordering_category</code>.
     */
    val ORDERING_CATEGORY: TableField<Record, String?> = createField(DSL.name("ordering_category"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.ordering_routine_catalog</code>.
     */
    val ORDERING_ROUTINE_CATALOG: TableField<Record, String?> = createField(DSL.name("ordering_routine_catalog"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.ordering_routine_schema</code>.
     */
    val ORDERING_ROUTINE_SCHEMA: TableField<Record, String?> = createField(DSL.name("ordering_routine_schema"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.ordering_routine_name</code>.
     */
    val ORDERING_ROUTINE_NAME: TableField<Record, String?> = createField(DSL.name("ordering_routine_name"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.reference_type</code>.
     */
    val REFERENCE_TYPE: TableField<Record, String?> = createField(DSL.name("reference_type"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>information_schema.user_defined_types.data_type</code>.
     */
    val DATA_TYPE: TableField<Record, String?> = createField(DSL.name("data_type"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.character_maximum_length</code>.
     */
    val CHARACTER_MAXIMUM_LENGTH: TableField<Record, Int?> = createField(DSL.name("character_maximum_length"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.character_octet_length</code>.
     */
    val CHARACTER_OCTET_LENGTH: TableField<Record, Int?> = createField(DSL.name("character_octet_length"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.character_set_catalog</code>.
     */
    val CHARACTER_SET_CATALOG: TableField<Record, String?> = createField(DSL.name("character_set_catalog"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.character_set_schema</code>.
     */
    val CHARACTER_SET_SCHEMA: TableField<Record, String?> = createField(DSL.name("character_set_schema"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.character_set_name</code>.
     */
    val CHARACTER_SET_NAME: TableField<Record, String?> = createField(DSL.name("character_set_name"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.collation_catalog</code>.
     */
    val COLLATION_CATALOG: TableField<Record, String?> = createField(DSL.name("collation_catalog"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.collation_schema</code>.
     */
    val COLLATION_SCHEMA: TableField<Record, String?> = createField(DSL.name("collation_schema"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.collation_name</code>.
     */
    val COLLATION_NAME: TableField<Record, String?> = createField(DSL.name("collation_name"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.numeric_precision</code>.
     */
    val NUMERIC_PRECISION: TableField<Record, Int?> = createField(DSL.name("numeric_precision"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.numeric_precision_radix</code>.
     */
    val NUMERIC_PRECISION_RADIX: TableField<Record, Int?> = createField(DSL.name("numeric_precision_radix"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.numeric_scale</code>.
     */
    val NUMERIC_SCALE: TableField<Record, Int?> = createField(DSL.name("numeric_scale"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.datetime_precision</code>.
     */
    val DATETIME_PRECISION: TableField<Record, Int?> = createField(DSL.name("datetime_precision"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.interval_type</code>.
     */
    val INTERVAL_TYPE: TableField<Record, String?> = createField(DSL.name("interval_type"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.interval_precision</code>.
     */
    val INTERVAL_PRECISION: TableField<Record, Int?> = createField(DSL.name("interval_precision"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.source_dtd_identifier</code>.
     */
    val SOURCE_DTD_IDENTIFIER: TableField<Record, String?> = createField(DSL.name("source_dtd_identifier"), SQLDataType.VARCHAR, this, "")

    /**
     * The column
     * <code>information_schema.user_defined_types.ref_dtd_identifier</code>.
     */
    val REF_DTD_IDENTIFIER: TableField<Record, String?> = createField(DSL.name("ref_dtd_identifier"), SQLDataType.VARCHAR, this, "")

    private constructor(alias: Name, aliased: Table<Record>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>information_schema.user_defined_types</code>
     * table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>information_schema.user_defined_types</code>
     * table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>information_schema.user_defined_types</code> table
     * reference
     */
    constructor(): this(DSL.name("user_defined_types"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, Record>): this(Internal.createPathAlias(child, key), child, key, USER_DEFINED_TYPES, null)
    override fun getSchema(): Schema? = if (aliased()) null else InformationSchema.INFORMATION_SCHEMA
    override fun `as`(alias: String): UserDefinedTypes = UserDefinedTypes(DSL.name(alias), this)
    override fun `as`(alias: Name): UserDefinedTypes = UserDefinedTypes(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserDefinedTypes = UserDefinedTypes(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserDefinedTypes = UserDefinedTypes(name, null)
}
