/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.information_schema.tables


import fi.hsl.jore.jore4.jooq.information_schema.InformationSchema

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Views(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?
): TableImpl<Record>(
    alias,
    InformationSchema.INFORMATION_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.view()
) {
    companion object {

        /**
         * The reference instance of <code>information_schema.views</code>
         */
        val VIEWS: Views = Views()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>information_schema.views.table_catalog</code>.
     */
    val TABLE_CATALOG: TableField<Record, String?> = createField(DSL.name("table_catalog"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>information_schema.views.table_schema</code>.
     */
    val TABLE_SCHEMA: TableField<Record, String?> = createField(DSL.name("table_schema"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>information_schema.views.table_name</code>.
     */
    val TABLE_NAME: TableField<Record, String?> = createField(DSL.name("table_name"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>information_schema.views.view_definition</code>.
     */
    val VIEW_DEFINITION: TableField<Record, String?> = createField(DSL.name("view_definition"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>information_schema.views.check_option</code>.
     */
    val CHECK_OPTION: TableField<Record, String?> = createField(DSL.name("check_option"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>information_schema.views.is_updatable</code>.
     */
    val IS_UPDATABLE: TableField<Record, String?> = createField(DSL.name("is_updatable"), SQLDataType.VARCHAR(3), this, "")

    /**
     * The column <code>information_schema.views.is_insertable_into</code>.
     */
    val IS_INSERTABLE_INTO: TableField<Record, String?> = createField(DSL.name("is_insertable_into"), SQLDataType.VARCHAR(3), this, "")

    /**
     * The column <code>information_schema.views.is_trigger_updatable</code>.
     */
    val IS_TRIGGER_UPDATABLE: TableField<Record, String?> = createField(DSL.name("is_trigger_updatable"), SQLDataType.VARCHAR(3), this, "")

    /**
     * The column <code>information_schema.views.is_trigger_deletable</code>.
     */
    val IS_TRIGGER_DELETABLE: TableField<Record, String?> = createField(DSL.name("is_trigger_deletable"), SQLDataType.VARCHAR(3), this, "")

    /**
     * The column
     * <code>information_schema.views.is_trigger_insertable_into</code>.
     */
    val IS_TRIGGER_INSERTABLE_INTO: TableField<Record, String?> = createField(DSL.name("is_trigger_insertable_into"), SQLDataType.VARCHAR(3), this, "")

    private constructor(alias: Name, aliased: Table<Record>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>information_schema.views</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>information_schema.views</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>information_schema.views</code> table reference
     */
    constructor(): this(DSL.name("views"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, Record>): this(Internal.createPathAlias(child, key), child, key, VIEWS, null)
    override fun getSchema(): Schema? = if (aliased()) null else InformationSchema.INFORMATION_SCHEMA
    override fun `as`(alias: String): Views = Views(DSL.name(alias), this)
    override fun `as`(alias: Name): Views = Views(alias, this)
    override fun `as`(alias: Table<*>): Views = Views(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Views = Views(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Views = Views(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Views = Views(name.getQualifiedName(), null)
}
