/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.`public`


import fi.hsl.jore.jore4.jooq.DefaultCatalog

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Configuration
import org.jooq.Field
import org.jooq.Record
import org.jooq.Result
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.pgp_armor_headers</code>.
     */
    val PGP_ARMOR_HEADERS: fi.hsl.jore.jore4.jooq.`public`.tables.PgpArmorHeaders get() = fi.hsl.jore.jore4.jooq.`public`.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS

    /**
     * Call <code>public.pgp_armor_headers</code>.
     */
    fun PGP_ARMOR_HEADERS(
          configuration: Configuration
        , __1: String?
    ): Result<Record> = configuration.dsl().selectFrom(fi.hsl.jore.jore4.jooq.`public`.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
          __1
    )).fetch()

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    fun PGP_ARMOR_HEADERS(
          __1: String?
    ): fi.hsl.jore.jore4.jooq.`public`.tables.PgpArmorHeaders = fi.hsl.jore.jore4.jooq.`public`.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
        __1
    )

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    fun PGP_ARMOR_HEADERS(
          __1: Field<String?>
    ): fi.hsl.jore.jore4.jooq.`public`.tables.PgpArmorHeaders = fi.hsl.jore.jore4.jooq.`public`.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
        __1
    )

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        fi.hsl.jore.jore4.jooq.`public`.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS
    )
}
