/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.vehicle_journey.tables.references


import fi.hsl.jore.jore4.jooq.vehicle_journey.tables.JourneyType
import fi.hsl.jore.jore4.jooq.vehicle_journey.tables.VehicleJourney



/**
 * Enum table for defining allowed journey types.
 */
val JOURNEY_TYPE: JourneyType = JourneyType.JOURNEY_TYPE

/**
 * The planned movement of a public transport vehicle on a DAY TYPE from the
 * start point to the end point of a JOURNEY PATTERN on a specified ROUTE.
 * Transmodel: https://www.transmodel-cen.eu/model/index.htm?goto=3:1:1:831 
 */
val VEHICLE_JOURNEY_: VehicleJourney = VehicleJourney.VEHICLE_JOURNEY_
