/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.internal_service_calendar.routines.references


import fi.hsl.jore.jore4.jooq.internal_service_calendar.routines.GetSubstituteOperatingPeriodBeginDate
import fi.hsl.jore.jore4.jooq.internal_service_calendar.routines.GetSubstituteOperatingPeriodEndDate

import java.time.LocalDate
import java.util.UUID

import org.jooq.Configuration
import org.jooq.Field



/**
 * Call
 * <code>internal_service_calendar.get_substitute_operating_period_begin_date</code>
 */
fun getSubstituteOperatingPeriodBeginDate(
      configuration: Configuration
    , substituteOperatingPeriodUuid: UUID?
): LocalDate? {
    val f = GetSubstituteOperatingPeriodBeginDate()
    f.setSubstituteOperatingPeriodUuid(substituteOperatingPeriodUuid)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get
 * <code>internal_service_calendar.get_substitute_operating_period_begin_date</code>
 * as a field.
 */
fun getSubstituteOperatingPeriodBeginDate(
      substituteOperatingPeriodUuid: UUID?
): Field<LocalDate?> {
    val f = GetSubstituteOperatingPeriodBeginDate()
    f.setSubstituteOperatingPeriodUuid(substituteOperatingPeriodUuid)

    return f.asField()
}

/**
 * Get
 * <code>internal_service_calendar.get_substitute_operating_period_begin_date</code>
 * as a field.
 */
fun getSubstituteOperatingPeriodBeginDate(
      substituteOperatingPeriodUuid: Field<UUID?>
): Field<LocalDate?> {
    val f = GetSubstituteOperatingPeriodBeginDate()
    f.setSubstituteOperatingPeriodUuid(substituteOperatingPeriodUuid)

    return f.asField()
}

/**
 * Call
 * <code>internal_service_calendar.get_substitute_operating_period_end_date</code>
 */
fun getSubstituteOperatingPeriodEndDate(
      configuration: Configuration
    , substituteOperatingPeriodUuid: UUID?
): LocalDate? {
    val f = GetSubstituteOperatingPeriodEndDate()
    f.setSubstituteOperatingPeriodUuid(substituteOperatingPeriodUuid)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get
 * <code>internal_service_calendar.get_substitute_operating_period_end_date</code>
 * as a field.
 */
fun getSubstituteOperatingPeriodEndDate(
      substituteOperatingPeriodUuid: UUID?
): Field<LocalDate?> {
    val f = GetSubstituteOperatingPeriodEndDate()
    f.setSubstituteOperatingPeriodUuid(substituteOperatingPeriodUuid)

    return f.asField()
}

/**
 * Get
 * <code>internal_service_calendar.get_substitute_operating_period_end_date</code>
 * as a field.
 */
fun getSubstituteOperatingPeriodEndDate(
      substituteOperatingPeriodUuid: Field<UUID?>
): Field<LocalDate?> {
    val f = GetSubstituteOperatingPeriodEndDate()
    f.setSubstituteOperatingPeriodUuid(substituteOperatingPeriodUuid)

    return f.asField()
}
