/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.return_value.tables


import fi.hsl.jore.jore4.jooq.return_value.ReturnValue
import fi.hsl.jore.jore4.jooq.return_value.tables.records.VehicleScheduleRecord

import java.time.LocalDate
import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This return value table is used in function
 * vehicle_journey.get_vehicle_schedules_on_date. It consists of
 * vehicle_journey_id, vehicle_schedule_frame_id or
 * substitute_operating_day_by_line_type_id and also enriched with data, which
 * are used in the UI side.
 */
@Suppress("UNCHECKED_CAST")
open class VehicleSchedule(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, VehicleScheduleRecord>?,
    parentPath: InverseForeignKey<out Record, VehicleScheduleRecord>?,
    aliased: Table<VehicleScheduleRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<VehicleScheduleRecord>(
    alias,
    ReturnValue.RETURN_VALUE,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment("This return value table is used in function vehicle_journey.get_vehicle_schedules_on_date. It consists of vehicle_journey_id, vehicle_schedule_frame_id or\nsubstitute_operating_day_by_line_type_id and also enriched with data, which are used in the UI side."),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>return_value.vehicle_schedule</code>
         */
        val VEHICLE_SCHEDULE: VehicleSchedule = VehicleSchedule()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<VehicleScheduleRecord> = VehicleScheduleRecord::class.java

    /**
     * The column <code>return_value.vehicle_schedule.vehicle_journey_id</code>.
     */
    val VEHICLE_JOURNEY_ID: TableField<VehicleScheduleRecord, UUID?> = createField(DSL.name("vehicle_journey_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>return_value.vehicle_schedule.validity_start</code>.
     */
    val VALIDITY_START: TableField<VehicleScheduleRecord, LocalDate?> = createField(DSL.name("validity_start"), SQLDataType.LOCALDATE.nullable(false), this, "")

    /**
     * The column <code>return_value.vehicle_schedule.validity_end</code>.
     */
    val VALIDITY_END: TableField<VehicleScheduleRecord, LocalDate?> = createField(DSL.name("validity_end"), SQLDataType.LOCALDATE.nullable(false), this, "")

    /**
     * The column <code>return_value.vehicle_schedule.priority</code>.
     */
    val PRIORITY: TableField<VehicleScheduleRecord, Int?> = createField(DSL.name("priority"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>return_value.vehicle_schedule.day_type_id</code>.
     */
    val DAY_TYPE_ID: TableField<VehicleScheduleRecord, UUID?> = createField(DSL.name("day_type_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column
     * <code>return_value.vehicle_schedule.vehicle_schedule_frame_id</code>.
     */
    val VEHICLE_SCHEDULE_FRAME_ID: TableField<VehicleScheduleRecord, UUID?> = createField(DSL.name("vehicle_schedule_frame_id"), SQLDataType.UUID, this, "")

    /**
     * The column
     * <code>return_value.vehicle_schedule.substitute_operating_day_by_line_type_id</code>.
     */
    val SUBSTITUTE_OPERATING_DAY_BY_LINE_TYPE_ID: TableField<VehicleScheduleRecord, UUID?> = createField(DSL.name("substitute_operating_day_by_line_type_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>return_value.vehicle_schedule.created_at</code>.
     */
    val CREATED_AT: TableField<VehicleScheduleRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    private constructor(alias: Name, aliased: Table<VehicleScheduleRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<VehicleScheduleRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<VehicleScheduleRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>return_value.vehicle_schedule</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>return_value.vehicle_schedule</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>return_value.vehicle_schedule</code> table reference
     */
    constructor(): this(DSL.name("vehicle_schedule"), null)
    override fun getSchema(): Schema? = if (aliased()) null else ReturnValue.RETURN_VALUE
    override fun `as`(alias: String): VehicleSchedule = VehicleSchedule(DSL.name(alias), this)
    override fun `as`(alias: Name): VehicleSchedule = VehicleSchedule(alias, this)
    override fun `as`(alias: Table<*>): VehicleSchedule = VehicleSchedule(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): VehicleSchedule = VehicleSchedule(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): VehicleSchedule = VehicleSchedule(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): VehicleSchedule = VehicleSchedule(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): VehicleSchedule = VehicleSchedule(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): VehicleSchedule = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): VehicleSchedule = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): VehicleSchedule = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): VehicleSchedule = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): VehicleSchedule = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): VehicleSchedule = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): VehicleSchedule = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): VehicleSchedule = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): VehicleSchedule = where(DSL.notExists(select))
}
