/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.vehicle_schedule.routines


import fi.hsl.jore.jore4.jooq.vehicle_schedule.VehicleSchedule

import org.jooq.impl.AbstractRoutine


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ValidateQueuedSchedulesUniqueness : AbstractRoutine<java.lang.Void>("validate_queued_schedules_uniqueness", VehicleSchedule.VEHICLE_SCHEDULE) {
    companion object {
    }

    init {
    }
}
