/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.vehicle_schedule.keys


import fi.hsl.jore.jore4.jooq.vehicle_schedule.tables.VehicleScheduleFrame

import org.jooq.Record
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val VEHICLE_SCHEDULE_FRAME_PKEY: UniqueKey<Record> = Internal.createUniqueKey(VehicleScheduleFrame.VEHICLE_SCHEDULE_FRAME, DSL.name("vehicle_schedule_frame_pkey"), arrayOf(VehicleScheduleFrame.VEHICLE_SCHEDULE_FRAME.VEHICLE_SCHEDULE_FRAME_ID), true)
