name: CD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  run_kotlin_tests:
    name: Run kotlin tests
    uses: ./.github/workflows/run-kotlin-tests.yml

  publish_docker_image_to_acr:
    needs:
      - run_kotlin_tests
    name: Publish Docker image to ACR
    permissions:
      id-token: write
      contents: read
    uses: HSLdevcom/jore4-tools/.github/workflows/shared-build-and-publish-docker-image.yml@shared-build-and-publish-docker-image-v1
    with:
      docker_image_name: jore4-timetables-api
      build_arm64_image: true
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  run_cypress_tests:
    name: Run E2E tests
    needs:
      - run_kotlin_tests
      - publish_docker_image_to_acr
    uses: HSLdevcom/jore4-tools/.github/workflows/shared-run-e2e.yml@main
    with:
      timetablesapi_version: "${{ needs.publish_docker_image_to_acr.outputs.docker_image }}"
