name: Run java tests

on:
  push:
  pull_request:
    branches: [main]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-tests:
    name: Run java tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start dependencies (blocking until up)
        run: ./development.sh start:deps

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          java-package: jdk
          architecture: x64
          distribution: temurin

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests and try building a package
        run: |
          # create mandatory Maven configuration file for runner user
          RUNNER_USERNAME=$(whoami)
          touch ./profiles/dev/config.${RUNNER_USERNAME}.properties

          # run tests
          mvn clean verify
