name: Test whether the dockerized version works

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test-docker-compose:
    name: verify docker-compose setup
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start development dependencies and the timetables service
        run: ./development.sh start

      - name: Verify that dockerized timetables API is up and running
        uses: HSLdevcom/jore4-tools/github-actions/healthcheck@healthcheck-v1
        with:
          command:
            "curl --fail http://localhost:3009/actuator/health --output
            /dev/null --silent"
